from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[1]

MODEL_PATH = ROOT_DIR / "models" / "hand_landmarker.task"
CLASSIFIER_PATH = ROOT_DIR / "models" / "gesture_model.npz"
LABELS_PATH = ROOT_DIR / "data" / "labels.json"

CAMERA_INDEX = 0

FRAME_WIDTH = 480
FRAME_HEIGHT = 360
TARGET_FPS = 15

JPEG_QUALITY = 65

MIN_HAND_DETECTION_CONFIDENCE = 0.5
MIN_HAND_PRESENCE_CONFIDENCE = 0.5
MIN_TRACKING_CONFIDENCE = 0.5

CLASSIFIER_CONFIDENCE_THRESHOLD = 0.70

SMOOTHING_WINDOW = 7
MIN_STABLE_COUNT = 5

SPEECH_COOLDOWN_SECONDS = 1.5

WEB_HOST = "0.0.0.0"
WEB_PORT = 5000